image: debian:10.8

build:
  image: ubuntu
  stage: build
  tags:
    - linux

  before_script:
    - apt update
    - apt install -y gcc make python3-pip python3
    - python3 -m pip install poetry

  script:
    - make ci
    - bash .ci/debian10.sh

test-aws-debian:
  image: debian:10.8
  stage: test
  tags:
    - linux
  script:
    - apt update && apt install -y python3-pip sudo
    - python3 -m pip install poetry pip wheel --upgrade
    - python3 -m pip install .
    - export PATH=$HOME/.local/bin:$PATH
    - bmo subcom script caddy_debian.sh
    - bmo subcom script node_exporter.sh
