name: Linux

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build and test"
        run: |
          python -m pip -y install poetry
          poetry install 
          poetry run pytest 
          poetry run mypy bmo
