name: Linux

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build and test"
        uses: jiro4989/setup-nim-action@v1
        run: nimble build -y
        run: nimble test
        run: testament pat "tests/test*.nim"

      - name: "Build docs"
        run: nimble html

      - name: "Deploy Pages"
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'ref/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmldocs
    
