name: Windows

on: [push]

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: pwsh
      - run: |
          choco install nim -y
          refreshenv
          echo "Checking for installed binaries"
          nim -v
          nimble -v
      
