name: Windows

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name : "Build and test"
        run: |
          powershell.exe -F ./.ci/build_and_test_windows.ps1
