name: Windows

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name : "Build and test"
        run: |
          python -m ensurepip
          python -m pip install pip --upgrade
          python -m pip install poetry --upgrade
          python -m poetry install
          python -m poetry run mypy bmo 
          python -m poetry run pylint -E .

