name: Windows

on: push

jobs:
  bmo:
    runs-on: windows-latest
    steps:
    - name: Setup Nim
      uses: actions/checkout@v2
      shell: pwsh
      run: |
        choco install nim -y
        refreshenv
        echo "Checking for installed binaries"
        nim -v
        nimble -v
      
