name: Windows

on: [push]

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          choco install nim -y
          refreshenv
          echo $env:path
          nim.exe -v
          nimble.exe -v
      
