name: Windows

on: push

jobs:
  bmo:
    runs-on: windows-latest
    steps:
    - name: Setup Nim
      run: |
        choco install nim -y
        RefreshEnv
        nim -v
        nimble -v
      
