name: Windows

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - run: nimble build -y
      - run: nimble test
      - run: testament pat "tests/test*.nim"
